"""empty message

Revision ID: 00cfb8e3cda2
Revises: 5bcab16f3a5e
Create Date: 2022-04-09 23:27:13.995399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cfb8e3cda2'
down_revision = '5bcab16f3a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'precio_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pedidos', 'metodo_de_pago',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'metodo_de_pago',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pedidos', 'precio_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
