"""empty message

Revision ID: 147bed2c47bd
Revises: 9b4e44294408
Create Date: 2022-04-04 23:06:02.919903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147bed2c47bd'
down_revision = '9b4e44294408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
