"""empty message

Revision ID: 2bf9078adb5f
Revises: e7f3244ecbee
Create Date: 2022-04-10 21:53:55.543927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf9078adb5f'
down_revision = 'e7f3244ecbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cursos', 'description',
               existing_type=sa.VARCHAR(length=600),
               nullable=False)
    op.alter_column('cursos', 'categoria',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('cursos', 'precio',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('pedidos', sa.Column('curso_id', sa.Integer(), nullable=True))
    op.add_column('pedidos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pedidos', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'pedidos', 'cursos', ['curso_id'], ['id'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'user_id')
    op.drop_column('pedidos', 'curso_id')
    op.alter_column('cursos', 'precio',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cursos', 'categoria',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('cursos', 'description',
               existing_type=sa.VARCHAR(length=600),
               nullable=True)
    # ### end Alembic commands ###
