"""empty message

<<<<<<< HEAD:migrations/versions/5219cc3a0c31_.py
Revision ID: 5219cc3a0c31
Revises: be5a8e3cfb9a
Create Date: 2022-04-08 23:47:11.447868
=======
Revision ID: 6baa3d5ac1cc
Revises: e338bfd1b20e
Create Date: 2022-04-08 23:52:06.200684
>>>>>>> dev:migrations/versions/6baa3d5ac1cc_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/5219cc3a0c31_.py
revision = '5219cc3a0c31'
down_revision = 'be5a8e3cfb9a'
=======
revision = '6baa3d5ac1cc'
down_revision = 'e338bfd1b20e'
>>>>>>> dev:migrations/versions/6baa3d5ac1cc_.py
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
