"""empty message

<<<<<<< HEAD:migrations/versions/b75457461aca_.py
Revision ID: b75457461aca
Revises: 
Create Date: 2022-04-17 00:21:07.182963
=======
Revision ID: 9b16f6e1640b
Revises: 
Create Date: 2022-04-17 00:43:19.165418
>>>>>>> dev:migrations/versions/9b16f6e1640b_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/b75457461aca_.py
revision = 'b75457461aca'
=======
revision = '9b16f6e1640b'
>>>>>>> dev:migrations/versions/9b16f6e1640b_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
<<<<<<< HEAD:migrations/versions/b75457461aca_.py
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=600), nullable=True),
    sa.Column('url_portada', sa.String(length=600), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
=======
    sa.Column('description', sa.String(length=600), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('url_portada', sa.String(length=300), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=False),
>>>>>>> dev:migrations/versions/9b16f6e1640b_.py
    sa.Column('duracion', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precio_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metodo_de_pago', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('cursos')
    op.drop_table('user')
    # ### end Alembic commands ###
