"""empty message

Revision ID: e7f3244ecbee
Revises: eafe47bc6d72
Create Date: 2022-04-08 23:21:34.624360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f3244ecbee'
down_revision = 'eafe47bc6d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('name', sa.String(length=300), nullable=True))
    op.drop_constraint('cursos_user_id_fkey', 'cursos', type_='foreignkey')
    op.create_foreign_key(None, 'cursos', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cursos', 'nombre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('nombre', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cursos', type_='foreignkey')
    op.create_foreign_key('cursos_user_id_fkey', 'cursos', 'user', ['user_id'], ['id'])
    op.drop_column('cursos', 'name')
    # ### end Alembic commands ###
