"""empty message

Revision ID: f51562a543a0
Revises: 946594f41a7a
Create Date: 2022-04-13 23:40:35.754650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51562a543a0'
down_revision = '946594f41a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cursos', 'precio',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cursos', 'precio',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
